CREATE OR REPLACE VIEW DICE_DEV.PERSIST.VW_COMPONENT_DB_MASKED
AS
SELECT
  "Serial_No" AS "Serial_No",
  "Unique ID" AS "Unique ID",
  "Part Description" AS "Part Description",
  "Part Photograph" AS "Part Photograph",
  "Vehicle Model" AS "Vehicle Model",
  "OEM" AS "OEM",
  "L1-Aggregate" AS "L1-Aggregate",
  "L2-Subsystem" AS "L2-Subsystem",
  "L3-Commodity" AS "L3-Commodity",
  "L4-Commodity Type" AS "L4-Commodity Type",
  "L5- Component Type" AS "L5- Component Type",
  "Child Part ID" AS "Child Part ID",
  "Child Part Description" AS "Child Part Description",
  "Child Part Photograph" AS "Child Part Photograph",
  "Child Part #" AS "Child Part #",
  "Year" AS "Year",
  "Currency" AS "Currency",
  "BOM Price" AS "BOM Price",
  "Landed Price" AS "Landed Price",
  "# of bought out parts" AS "# of bought out parts",
  "Total cost" AS "Total cost",
  "Length" AS "Length",
  "Length Units" AS "Length Units",
  "Breadth" AS "Breadth",
  "Breadth Units" AS "Breadth Units",
  "Height" AS "Height",
  "Height Units" AS "Height Units",
  "Thickness" AS "Thickness",
  "Thickness Units" AS "Thickness Units",
  "Width" AS "Width",
  "Width Units" AS "Width Units",
  "Diameter" AS "Diameter",
  "Diameter Units" AS "Diameter Units",
  "Outer Diameter" AS "Outer Diameter",
  "Outer Diameter Units" AS "Outer Diameter Units",
  "Inner Diameter" AS "Inner Diameter",
  "Inner Diameter Units" AS "Inner Diameter Units",
  "Pitch" AS "Pitch",
  "Pitch Units" AS "Pitch Units",
  "Threadsize" AS "Threadsize",
  "Threadsize Units" AS "Threadsize Units",
  "Head Type" AS "Head Type",
  "Product Grade" AS "Product Grade",
  "Gross Weight" AS "Gross Weight",
  "Gross Weight Units" AS "Gross Weight Units",
  "Finished Weight" AS "Finished Weight",
  "Finished Weight Units" AS "Finished Weight Units",
  "Yield" AS "Yield",
  "Material Specifications" AS "Material Specifications",
  "Process Type Name" AS "Process Type Name",
  "Process Type" AS "Process Type",
  "Process Type Specifics" AS "Process Type Specifics",
  "Use Place" AS "Use Place",
  "Surface Finish Type" AS "Surface Finish Type",
  "Treatment Type" AS "Treatment Type",
  "Hardening Type" AS "Hardening Type",
  "Color" AS "Color",
  "Physical Specifications" AS "Physical Specifications",
  "Electrical/Electronics Specifications" AS "Electrical/Electronics Specifications",
  "Purpose" AS "Purpose",
  "Mode of Update" AS "Mode of Update",
  "Component Supplier Name" AS "Component Supplier Name",
  "Supplier SOB" AS "Supplier SOB",
  "Country" AS "Country",
  "Child Part Supplier" AS "Child Part Supplier",
  "Child Part Country" AS "Child Part Country"
FROM DICE_DEV.PERSIST.COMPONENT_DB
WHERE "IS_CURRENT" = 'Y';