CREATE OR REPLACE VIEW DICE_DEV.PERSIST.VW_MODEL_DB_MASKED
AS
SELECT
  "Model Name" AS "Model Name",
  "OEM" AS "OEM",
  "Year" AS "Year",
  "Vehicle Type" AS "Vehicle Type",
  "Segment" AS "Segment",
  "Currency" AS "Currency",
  "Retail Price" AS "Retail Price",
  "BOM Price" AS "BOM Price",
  "Length" AS "Length",
  "Length Units" AS "Length Units",
  "Width" AS "Width",
  "Width Units" AS "Width Units",
  "Height" AS "Height",
  "Height Units" AS "Height Units",
  "Kerb Weight" AS "Kerb Weight",
  "Kerb Weight Units" AS "Kerb Weight Units",
  "Gross Weight" AS "Gross Weight",
  "Gross Weight Units" AS "Gross Weight Units",
  "Payload" AS "Payload",
  "Payload Units" AS "Payload Units",
  "Seating Capacity" AS "Seating Capacity",
  "Seat Type" AS "Seat Type",
  "Seat Layout" AS "Seat Layout",
  "# of doors" AS "# of doors",
  "Boot Space" AS "Boot Space",
  "Boot Space Units" AS "Boot Space Units",
  "Fuel Capacity" AS "Fuel Capacity",
  "Fuel Capacity Units" AS "Fuel Capacity Units",
  "Engine Type" AS "Engine Type",
  "Engine Location" AS "Engine Location",
  "Engine Capacity" AS "Engine Capacity",
  "# of cylinders" AS "# of cylinders",
  "# of valves" AS "# of valves",
  "Cooling System" AS "Cooling System",
  "Start Type" AS "Start Type",
  "Fuel Type" AS "Fuel Type",
  "Fuel Supply" AS "Fuel Supply",
  "Ignition Type" AS "Ignition Type",
  "Transmission" AS "Transmission",
  "Gear Box" AS "Gear Box",
  "Clutch Type" AS "Clutch Type",
  "Drive Type" AS "Drive Type",
  "Emission Standard" AS "Emission Standard",
  "Chassis Type" AS "Chassis Type",
  "Body Type" AS "Body Type",
  "Floor type" AS "Floor type",
  "Axle Configuration" AS "Axle Configuration",
  "Front Axle" AS "Front Axle",
  "Rear Axle" AS "Rear Axle",
  "Front Suspension" AS "Front Suspension",
  "Rear Suspension" AS "Rear Suspension",
  "Steering Type" AS "Steering Type",
  "Steering Column" AS "Steering Column",
  "Steering Gear" AS "Steering Gear",
  "Front Tyre Type" AS "Front Tyre Type",
  "Rear Tyre Type" AS "Rear Tyre Type",
  "Front Wheel Type" AS "Front Wheel Type",
  "Rear Wheel Type" AS "Rear Wheel Type",
  "Front Brake Type" AS "Front Brake Type",
  "Rear Brake Type" AS "Rear Brake Type"
FROM DICE_DEV.PERSIST.MODEL_DB
WHERE "IS_CURRENT" = 'Y';