CREATE OR REPLACE VIEW DICE_DEV.PERSIST.VW_PRICING_DB_MASKED
AS
SELECT
"S_NO" AS "S_NO",
"Unique Part ID" AS "Unique Part ID",
"FSS/BTP Type" AS "FSS/BTP Type",
"Source of Idea (Project)" AS "Source of Idea (Project)",
"PART DESCRIPTION" AS "PART DESCRIPTION",
"SUPPLIER NAME" AS "SUPPLIER NAME",
"SUPPLIER_ID" AS "SUPPLIER_ID",
"2011" AS "2011",
"2015" AS "2015",
"2017" AS "2017",
"2018" AS "2018",
"2019" AS "2019",
"2020" AS "2020",
"Actual price / ZBC price / Market Benchmark" AS "Actual price / ZBC price / Market Benchmark",
"OEM GEOGRAPHY" AS "OEM GEOGRAPHY",
"CURRENCY" AS "CURRENCY",
"Product Segment" AS "Product Segment",
"L1 (AGGREGATE)" AS "L1 (AGGREGATE)",
"L2 (SUB-SYSTEM)" AS "L2 (SUB-SYSTEM)",
"L3 (COMMODITY)" AS "L3 (COMMODITY)",
"L4 (COMMODITY TYPE / MATERIAL)" AS "L4 (COMMODITY TYPE / MATERIAL)",
"L5 (COMPONENT TYPE)" AS "L5 (COMPONENT TYPE)",
"WEIGHT (KG)" AS "WEIGHT (KG)",
"TAG 1" AS "TAG 1",
"TAG 2" AS "TAG 2",
"TAG 3" AS "TAG 3",
"TAG 4" AS "TAG 4",
"TAG 5" AS "TAG 5",
"TAG 6" AS "TAG 6",
"TAG 7" AS "TAG 7",
"2011_Vol" AS "2011_Vol",
"2015_Vol" AS "2015_Vol",
"2017_Vol" AS "2017_Vol",
"2018_Vol" AS "2018_Vol",
"2019_Vol" AS "2019_Vol",
"2020_Vol" AS "2020_Vol",
"OEM price / Aftermarket price" AS "OEM price / Aftermarket price",
"SOURCE" AS "SOURCE",
"COMBINATION" AS "COMBINATION"
FROM DICE_DEV.PERSIST.PRICING_DB
WHERE "IS_CURRENT" = 'Y';